[package]
name = "pest_01"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Parser with pest"
authors = ["Hibskyi Vladyslav"]

[dependencies]
anyhow = "1.0.91"
pest = "2.7.14"
pest_derive = "2.7.14"
